---
name: Deploy Ansible Role to Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  galaxy_import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Ansible
        run: |
          pip install ansible-base
      - name: import galaxy
        run: |
          ansible-galaxy role import --api-key  "$API_KEY" $( echo ${GITHUB_REPOSITORY} | awk -F / '{print $1}') $( echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}')
        env:
          API_KEY: ${{ secrets.GALAXY_API_KEY }}
